### ISSUE TITLE
Smaller reproducer

### ISSUE THREAD

**Issue by radare** [Luis-Hebendanz/0pack#3]
Current 0pack is 17MB, which is too large to fit in our testsuite

**Comment by Qubasa** [comment]
I will look into it in the next few 3-4 weeks

**Comment by Qubasa** [comment]
@radare I made the binary smaller total is now ~7Mb. I hope this helps. Is the issue fixed now in radare?

**Comment by radare** [comment]
Thank you! i just merged the 7MB binary into the radare testsuite. That will hopefully soon be fixed and tested in master

**Comment by radare** [comment]
ftr https://github.com/radareorg/radare2/pull/14385
